Improve Travis CI setup and fix errors/warnings to run with modern compilers
g-truc/gli pull request #182
Opened 2020-11-28 20:28 UTC by AndyMender

2020-11-28 21:59 UTC, AndyMender commented on readme.md
> +| [Travis CI](https://travis-ci.org/g-truc/gli)| Linux 64 bits | Clang 7.0, Clang 9.0, GCC 7.4, GCC 9, GCC 10 | [![Travis CI](https://travis-ci.org/g-truc/gli.svg?branch=master)](https://travis-ci.or
The mentioned extra compiler compatibility. The `.travis.yml` config added to the PR provides configurations for these compilers.

2020-11-28 22:14 UTC, AndyMender commented on test/core/core_flip.cpp
> +		gli::detail::dxt1_block{ 63721, 255, { 228, 144, 64, 0 } },
Below are not code style fixes, The `gli::detail::dxt*_block` structs receive a different number number of arguments, but previous compilers would ignore this.

2020-11-29 09:02 UTC, AndyMender commented on .travis.yml
> -            - g++-4.9
I did remove the previous compiler build entries, but if they're still needed, I can re-add them.

2020-11-29 09:47 UTC, AndyMender commented on test/core/generate_mipmaps_sampler2d.cpp
> -		SamplerA.generate_mipmaps(gli::FILTER_LINEAR);
`gli::FILTER_LINEAR` fails some of the test iterations. It was replaced with the value of `Filter` passed to the `test` function.

2020-11-29 10:00 UTC, AndyMender commented
I removed most of the clean-up lines, but still left in changes like `int Error = 0` instead of `int Error(0)` and extra parentheses to make the `Error` logic operations in tests clearer. I can remove these as well if you consider them unneeded :).

2020-11-29 10:05 UTC, AndyMender commented on test/core/core_texture.cpp
> +		std::vector<int> Sizes = { 16, 32, 15, 17, 1 };
Debatable whether changes like these are needed. Theoretically, initializing the vector only once avoids the needless bookkeeping on `push_back` calls.

2020-11-29 10:09 UTC, AndyMender commented on test/core/core_texture.cpp
> -		printf("Generic texture creation performance test: %d\n", TimeEnd - TimeBegin);
A matter of opinion, but `std::cout` is a little more flexible when converting data to text and `std::endl` adds platform-specific newline symbols.

2020-12-10 09:05 UTC, christophe-lunarg requested changes
It's a bit unfortunate that so many changes obfuscate the actual work.

This said, it's more the compiler coverage that I am concerned about. It would be great to keep compatibility with old compilers.

2020-12-10 09:05 UTC, christophe-lunarg commented on test/core/test_size.cpp
> +			const gli::texture2d::size_type CurrentSize = Texture.size();
coding style use "const" after the type

2020-12-10 09:06 UTC, christophe-lunarg commented
These Travis C.I. changes are very welcome !

2020-12-10 22:27 UTC, AndyMender commented
I decided that it makes a little more sense to focus on the Travis CI setup alone and not mud it with additional commits. I opened a new PR here: https://github.com/g-truc/gli/pull/183

Fixes for compiler warnings can be tackled separately, I think.

2020-12-10 22:27 UTC, closed without merging